# Site settings
title: Bryan Lou
tagline: Software Engineer
description: > # this means to ignore newlines until "baseurl:"
      Personal Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://schildkopf.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Collections
# Add new slides as HTML files inside the _panels folder
collections:
  - panels