# Site settings
title: Bryan Lou
tagline: Software Engineer
description: > # this means to ignore newlines until "baseurl:"
      Personal Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://schildkopf.com" # the base hostname & protocol for your site

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: http://bryanlou.github.io/bryan_resume.pdf


# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Collections
# Add new slides as HTML files inside the _panels folder
collections:
  - panels